# Generated by Django 4.2.6 on 2023-10-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eadd', models.EmailField(max_length=100)),
                ('schd', models.TimeField()),
                ('cont', models.CharField(max_length=20000)),
            ],
        ),
    ]
