# Generated by Django 4.2.6 on 2023-10-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0004_rename_phno1_bot_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='phno',
            field=models.CharField(max_length=13),
        ),
    ]
