# Generated by Django 4.2.6 on 2023-10-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0006_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='cont',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='cont',
            new_name='content',
        ),
    ]
